// <auto-generated />
using System;
using CurlinggoSoft.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurlinggoSoft.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260816050553_AddIdentityTables")]
    partial class AddIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CurlinggoSoft.Models.Auditoria", b =>
                {
                    b.Property<long>("AuditoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditoriaID"));

                    b.Property<Guid?>("CorrelationID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DireccionIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RegistroID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UsuarioID")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ValoresAnterioresJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresNuevosJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditoriaID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Canton", b =>
                {
                    b.Property<int>("CantonID")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoDTA")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinciaID")
                        .HasColumnType("int");

                    b.HasKey("CantonID");

                    b.HasIndex("ProvinciaID");

                    b.ToTable("Cantones");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.CategoriaServicio", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaID"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaID");

                    b.ToTable("CategoriasServicio");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.ClientePerfil", b =>
                {
                    b.Property<string>("ClienteID")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CantonID")
                        .HasColumnType("int");

                    b.Property<string>("DireccionExacta")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DistritoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int>("ProvinciaID")
                        .HasColumnType("int");

                    b.HasKey("ClienteID");

                    b.HasIndex("CantonID");

                    b.HasIndex("DistritoID");

                    b.HasIndex("ProvinciaID");

                    b.ToTable("ClientesPerfil");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.DetallePrecioReserva", b =>
                {
                    b.Property<long>("DetallePrecioReservaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DetallePrecioReservaID"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int?>("OpcionPreguntaID")
                        .HasColumnType("int");

                    b.Property<long>("ReservaID")
                        .HasColumnType("bigint");

                    b.HasKey("DetallePrecioReservaID");

                    b.HasIndex("OpcionPreguntaID");

                    b.HasIndex("ReservaID");

                    b.ToTable("DetallePrecioReserva");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.DireccionCliente", b =>
                {
                    b.Property<long>("DireccionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DireccionID"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("CantonID")
                        .HasColumnType("int");

                    b.Property<string>("ClienteID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DireccionExacta")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("DistritoID")
                        .HasColumnType("int");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("NombreDireccion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("ProvinciaID")
                        .HasColumnType("int");

                    b.HasKey("DireccionID");

                    b.HasIndex("CantonID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("DistritoID");

                    b.HasIndex("ProvinciaID");

                    b.ToTable("DireccionesCliente");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.DisponibilidadTecnico", b =>
                {
                    b.Property<long>("DisponibilidadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DisponibilidadID"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<byte>("DiaSemana")
                        .HasColumnType("tinyint");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<string>("TecnicoID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DisponibilidadID");

                    b.HasIndex("TecnicoID");

                    b.ToTable("DisponibilidadTecnico");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Distrito", b =>
                {
                    b.Property<int>("DistritoID")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CantonID")
                        .HasColumnType("int");

                    b.Property<string>("CodigoDTA")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("DistritoID");

                    b.HasIndex("CantonID");

                    b.ToTable("Distritos");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.EstadoOfertaTecnico", b =>
                {
                    b.Property<int>("EstadoOfertaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoOfertaID"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EstadoOfertaID");

                    b.ToTable("EstadosOfertaTecnico");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.EstadoPago", b =>
                {
                    b.Property<int>("EstadoPagoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoPagoID"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EstadoPagoID");

                    b.ToTable("EstadosPago");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.EstadoReserva", b =>
                {
                    b.Property<int>("EstadoReservaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoReservaID"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrdenFlujo")
                        .HasColumnType("int");

                    b.HasKey("EstadoReservaID");

                    b.ToTable("EstadosReserva");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Evaluacion", b =>
                {
                    b.Property<long>("EvaluacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EvaluacionID"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EvaluadoUsuarioID")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EvaluadorUsuarioID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Puntuacion")
                        .HasColumnType("tinyint");

                    b.Property<long>("ReservaID")
                        .HasColumnType("bigint");

                    b.Property<int?>("ServicioID")
                        .HasColumnType("int");

                    b.Property<int>("TipoEvaluacionID")
                        .HasColumnType("int");

                    b.HasKey("EvaluacionID");

                    b.HasIndex("EvaluadoUsuarioID");

                    b.HasIndex("EvaluadorUsuarioID");

                    b.HasIndex("ReservaID");

                    b.HasIndex("ServicioID");

                    b.HasIndex("TipoEvaluacionID");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.HistorialEstadoReserva", b =>
                {
                    b.Property<long>("HistorialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("HistorialID"));

                    b.Property<int?>("EstadoAnteriorID")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("ReservaID")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioModificadorID")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("HistorialID");

                    b.HasIndex("EstadoAnteriorID");

                    b.HasIndex("EstadoNuevoID");

                    b.HasIndex("ReservaID");

                    b.HasIndex("UsuarioModificadorID");

                    b.ToTable("HistorialEstadosReserva");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.IntentoPago", b =>
                {
                    b.Property<long>("IntentoPagoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IntentoPagoID"));

                    b.Property<int>("EstadoPagoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIntento")
                        .HasColumnType("datetime2");

                    b.Property<string>("MensajeProveedor")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MetodoPagoID")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoIntento")
                        .HasColumnType("decimal(12,2)");

                    b.Property<long>("PagoID")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferenciaComprobante")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReferenciaProveedor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IntentoPagoID");

                    b.HasIndex("EstadoPagoID");

                    b.HasIndex("MetodoPagoID");

                    b.HasIndex("PagoID");

                    b.ToTable("IntentosPago");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.LogIntervencionOperativa", b =>
                {
                    b.Property<long>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogID"));

                    b.Property<string>("DatosEntradaJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecisionTomada")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModeloVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("ReservaID")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioIntervencionID")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LogID");

                    b.HasIndex("ReservaID");

                    b.HasIndex("UsuarioIntervencionID");

                    b.ToTable("LogsIntervencionOperativa");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Menu", b =>
                {
                    b.Property<long>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MenuID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Icono")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("MenuPadreID")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("MenuID");

                    b.HasIndex("MenuPadreID");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.MenuPermiso", b =>
                {
                    b.Property<long>("MenuID")
                        .HasColumnType("bigint");

                    b.Property<int>("PermisoID")
                        .HasColumnType("int");

                    b.HasKey("MenuID", "PermisoID");

                    b.HasIndex("PermisoID");

                    b.ToTable("MenuPermisos");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.MetodoPago", b =>
                {
                    b.Property<int>("MetodoPagoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetodoPagoID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MetodoPagoID");

                    b.ToTable("MetodosPago");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Notificacion", b =>
                {
                    b.Property<long>("NotificacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificacionID"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long?>("OfertaTecnicoID")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReservaID")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoNotificacion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UsuarioID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificacionID");

                    b.HasIndex("OfertaTecnicoID");

                    b.HasIndex("ReservaID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.OfertaTecnico", b =>
                {
                    b.Property<long>("OfertaTecnicoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OfertaTecnicoID"));

                    b.Property<decimal?>("DistanciaMetros")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("EstadoOfertaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrdenOferta")
                        .HasColumnType("int");

                    b.Property<long>("ReservaID")
                        .HasColumnType("bigint");

                    b.Property<string>("TecnicoID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OfertaTecnicoID");

                    b.HasIndex("EstadoOfertaID");

                    b.HasIndex("ReservaID");

                    b.HasIndex("TecnicoID");

                    b.ToTable("OfertasTecnico");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.OpcionPregunta", b =>
                {
                    b.Property<int>("OpcionPreguntaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpcionPreguntaID"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<decimal>("AjustePrecio")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("PreguntaServicioID")
                        .HasColumnType("int");

                    b.Property<string>("TextoOpcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Valor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OpcionPreguntaID");

                    b.HasIndex("PreguntaServicioID");

                    b.ToTable("OpcionesPregunta");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Pago", b =>
                {
                    b.Property<long>("PagoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PagoID"));

                    b.Property<decimal>("ComisionPlataforma")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("MontoNetoTecnico")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ProveedorPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ReservaID")
                        .HasColumnType("bigint");

                    b.HasKey("PagoID");

                    b.HasIndex("ReservaID");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Permiso", b =>
                {
                    b.Property<int>("PermisoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisoID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoPermiso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PermisoID");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.PreguntaServicio", b =>
                {
                    b.Property<int>("PreguntaServicioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreguntaServicioID"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<bool>("Obligatoria")
                        .HasColumnType("bit");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("ServicioID")
                        .HasColumnType("int");

                    b.Property<string>("TextoPregunta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoRespuesta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PreguntaServicioID");

                    b.HasIndex("ServicioID");

                    b.ToTable("PreguntasServicio");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Provincia", b =>
                {
                    b.Property<int>("ProvinciaID")
                        .HasColumnType("int");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoDTA")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProvinciaID");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.RespuestaReserva", b =>
                {
                    b.Property<long>("RespuestaReservaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RespuestaReservaID"));

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OpcionPreguntaID")
                        .HasColumnType("int");

                    b.Property<int>("PreguntaServicioID")
                        .HasColumnType("int");

                    b.Property<long>("ReservaID")
                        .HasColumnType("bigint");

                    b.Property<string>("RespuestaTexto")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("RespuestaReservaID");

                    b.HasIndex("OpcionPreguntaID");

                    b.HasIndex("PreguntaServicioID");

                    b.HasIndex("ReservaID");

                    b.ToTable("RespuestasReserva");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.RespuestaReservaOpcion", b =>
                {
                    b.Property<long>("RespuestaReservaOpcionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RespuestaReservaOpcionID"));

                    b.Property<int>("OpcionPreguntaID")
                        .HasColumnType("int");

                    b.Property<long>("RespuestaReservaID")
                        .HasColumnType("bigint");

                    b.HasKey("RespuestaReservaOpcionID");

                    b.HasIndex("OpcionPreguntaID");

                    b.HasIndex("RespuestaReservaID");

                    b.ToTable("RespuestasReservaOpciones");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Servicio", b =>
                {
                    b.Property<int>("ServicioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioID"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SubcategoriaID")
                        .HasColumnType("int");

                    b.Property<decimal>("TarifaDiagnosticoBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TiempoEstimadoMinutos")
                        .HasColumnType("int");

                    b.HasKey("ServicioID");

                    b.HasIndex("CategoriaID");

                    b.HasIndex("SubcategoriaID");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.SolicitudReserva", b =>
                {
                    b.Property<long>("ReservaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReservaID"));

                    b.Property<int?>("CantonID")
                        .HasColumnType("int");

                    b.Property<string>("ClienteID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("CodigoSeguimiento")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescripcionProblema")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long?>("DireccionID")
                        .HasColumnType("bigint");

                    b.Property<string>("DireccionServicio")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("DistritoID")
                        .HasColumnType("int");

                    b.Property<int>("DuracionEstimadaMinutos")
                        .HasColumnType("int");

                    b.Property<int>("EstadoReservaID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaHoraCompletada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraProgramada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LatitudServicio")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("LongitudServicio")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("MontoAjustes")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("MontoBaseCotizado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("MontoTotalCotizado")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("NotasCliente")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ProvinciaID")
                        .HasColumnType("int");

                    b.Property<int>("ServicioID")
                        .HasColumnType("int");

                    b.Property<string>("TecnicoID")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReservaID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("EstadoReservaID");

                    b.HasIndex("ServicioID");

                    b.HasIndex("TecnicoID");

                    b.ToTable("SolicitudesReserva");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.SubcategoriaServicio", b =>
                {
                    b.Property<int>("SubcategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubcategoriaID"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NombreSubcategoria")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("SubcategoriaID");

                    b.HasIndex("CategoriaID");

                    b.ToTable("SubcategoriasServicio");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.TecnicoEspecialidad", b =>
                {
                    b.Property<string>("TecnicoID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServicioID")
                        .HasColumnType("int");

                    b.Property<int>("AniosExperiencia")
                        .HasColumnType("int");

                    b.HasKey("TecnicoID", "ServicioID");

                    b.HasIndex("ServicioID");

                    b.ToTable("TecnicoEspecialidades");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.TecnicoPerfil", b =>
                {
                    b.Property<string>("TecnicoID")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CalificacionPromedio")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int?>("CantonCoberturaID")
                        .HasColumnType("int");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoVerificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaVerificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentificacionCedula")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("LatitudActual")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("LongitudActual")
                        .HasColumnType("decimal(9,6)");

                    b.Property<int?>("ProvinciaCoberturaID")
                        .HasColumnType("int");

                    b.HasKey("TecnicoID");

                    b.HasIndex("CantonCoberturaID");

                    b.HasIndex("ProvinciaCoberturaID");

                    b.ToTable("TecnicosPerfil");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.TecnicoUbicacionActual", b =>
                {
                    b.Property<string>("TecnicoID")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("TecnicoID");

                    b.ToTable("TecnicosUbicacionActual");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.TipoEvaluacion", b =>
                {
                    b.Property<int>("TipoEvaluacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoEvaluacionID"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TipoEvaluacionID");

                    b.ToTable("TiposEvaluacion");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Usuario", b =>
                {
                    b.Property<string>("UsuarioID")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EstadoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Auditoria", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Canton", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.ClientePerfil", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.Canton", "Canton")
                        .WithMany()
                        .HasForeignKey("CantonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("DistritoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Canton");

                    b.Navigation("Distrito");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.DetallePrecioReserva", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.OpcionPregunta", "Opcion")
                        .WithMany()
                        .HasForeignKey("OpcionPreguntaID");

                    b.HasOne("CurlinggoSoft.Models.SolicitudReserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opcion");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.DireccionCliente", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.Canton", "Canton")
                        .WithMany()
                        .HasForeignKey("CantonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.ClientePerfil", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("DistritoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("ProvinciaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Canton");

                    b.Navigation("Cliente");

                    b.Navigation("Distrito");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.DisponibilidadTecnico", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.TecnicoPerfil", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Distrito", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.Canton", "Canton")
                        .WithMany()
                        .HasForeignKey("CantonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Evaluacion", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.Usuario", "Evaluado")
                        .WithMany()
                        .HasForeignKey("EvaluadoUsuarioID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CurlinggoSoft.Models.Usuario", "Evaluador")
                        .WithMany()
                        .HasForeignKey("EvaluadorUsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.SolicitudReserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CurlinggoSoft.Models.TipoEvaluacion", "TipoEvaluacion")
                        .WithMany()
                        .HasForeignKey("TipoEvaluacionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluado");

                    b.Navigation("Evaluador");

                    b.Navigation("Reserva");

                    b.Navigation("Servicio");

                    b.Navigation("TipoEvaluacion");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.HistorialEstadoReserva", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.EstadoReserva", "EstadoAnterior")
                        .WithMany()
                        .HasForeignKey("EstadoAnteriorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CurlinggoSoft.Models.EstadoReserva", "EstadoNuevo")
                        .WithMany()
                        .HasForeignKey("EstadoNuevoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.SolicitudReserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.Usuario", "UsuarioModificador")
                        .WithMany()
                        .HasForeignKey("UsuarioModificadorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EstadoAnterior");

                    b.Navigation("EstadoNuevo");

                    b.Navigation("Reserva");

                    b.Navigation("UsuarioModificador");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.IntentoPago", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.EstadoPago", "EstadoPago")
                        .WithMany()
                        .HasForeignKey("EstadoPagoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.Pago", "Pago")
                        .WithMany()
                        .HasForeignKey("PagoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoPago");

                    b.Navigation("MetodoPago");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.LogIntervencionOperativa", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.SolicitudReserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CurlinggoSoft.Models.Usuario", "UsuarioIntervencion")
                        .WithMany()
                        .HasForeignKey("UsuarioIntervencionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Reserva");

                    b.Navigation("UsuarioIntervencion");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Menu", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.Menu", "MenuPadre")
                        .WithMany()
                        .HasForeignKey("MenuPadreID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MenuPadre");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.MenuPermiso", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Permiso");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Notificacion", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.OfertaTecnico", "OfertaTecnico")
                        .WithMany()
                        .HasForeignKey("OfertaTecnicoID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CurlinggoSoft.Models.SolicitudReserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CurlinggoSoft.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OfertaTecnico");

                    b.Navigation("Reserva");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.OfertaTecnico", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.EstadoOfertaTecnico", "EstadoOferta")
                        .WithMany()
                        .HasForeignKey("EstadoOfertaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.SolicitudReserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.TecnicoPerfil", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoOferta");

                    b.Navigation("Reserva");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.OpcionPregunta", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.PreguntaServicio", "Pregunta")
                        .WithMany()
                        .HasForeignKey("PreguntaServicioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Pago", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.SolicitudReserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.PreguntaServicio", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.RespuestaReserva", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.OpcionPregunta", "Opcion")
                        .WithMany()
                        .HasForeignKey("OpcionPreguntaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CurlinggoSoft.Models.PreguntaServicio", "Pregunta")
                        .WithMany()
                        .HasForeignKey("PreguntaServicioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.SolicitudReserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Opcion");

                    b.Navigation("Pregunta");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.RespuestaReservaOpcion", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.OpcionPregunta", "Opcion")
                        .WithMany()
                        .HasForeignKey("OpcionPreguntaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.RespuestaReserva", "RespuestaReserva")
                        .WithMany()
                        .HasForeignKey("RespuestaReservaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opcion");

                    b.Navigation("RespuestaReserva");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Servicio", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.CategoriaServicio", "Categoria")
                        .WithMany("Servicios")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.SubcategoriaServicio", "Subcategoria")
                        .WithMany("Servicios")
                        .HasForeignKey("SubcategoriaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.SolicitudReserva", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.ClientePerfil", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.EstadoReserva", "EstadoReserva")
                        .WithMany()
                        .HasForeignKey("EstadoReservaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.TecnicoPerfil", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");

                    b.Navigation("EstadoReserva");

                    b.Navigation("Servicio");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.SubcategoriaServicio", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.CategoriaServicio", "Categoria")
                        .WithMany("Subcategorias")
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.TecnicoEspecialidad", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CurlinggoSoft.Models.TecnicoPerfil", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Servicio");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.TecnicoPerfil", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.Canton", "CantonCobertura")
                        .WithMany()
                        .HasForeignKey("CantonCoberturaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CurlinggoSoft.Models.Provincia", "ProvinciaCobertura")
                        .WithMany()
                        .HasForeignKey("ProvinciaCoberturaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CantonCobertura");

                    b.Navigation("ProvinciaCobertura");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.TecnicoUbicacionActual", b =>
                {
                    b.HasOne("CurlinggoSoft.Models.TecnicoPerfil", "Tecnico")
                        .WithMany()
                        .HasForeignKey("TecnicoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.Usuario", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("CurlinggoSoft.Models.Usuario", "UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CurlinggoSoft.Models.CategoriaServicio", b =>
                {
                    b.Navigation("Servicios");

                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("CurlinggoSoft.Models.SubcategoriaServicio", b =>
                {
                    b.Navigation("Servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
